### ISSUE TITLE
手動加入設備名稱yeelink.light.fancl1的話，出現以下error:

### ISSUE THREAD

**Issue by oscarliuyc** [al-one/hass-miio-yeelink#19]
手動加入設備名稱yeelink.light.fancl1的話，出現以下error:

2021-06-09 14:07:39 ERROR (MainThread) [homeassistant.components.light] Error while setting up miio_yeelink platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/miio_yeelink/light.py", line 49, in async_setup_entry
await async_setup_platform(hass, config, async_add_entities)
File "/config/custom_components/miio_yeelink/light.py", line 59, in async_setup_platform
entity = MiotLightEntity(config)
File "/config/custom_components/miio_yeelink/__init__.py", line 880, in __init__
self._device = MiotDevice(self.mapping, host, token)
File "/usr/local/lib/python3.8/site-packages/miio/miot_device.py", line 48, in __init__
super().__init__(ip, token, start_id, debug, lazy_discover, timeout)
File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 151, in __init__
self._protocol = MiIOProtocol(
File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 43, in __init__
self.token = bytes.fromhex(token)
ValueError: non-hexadecimal number found in fromhex() arg at position 3
2021-06-09 14:07:39 ERROR (MainThread) [homeassistant.components.fan] Error while setting up miio_yeelink platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/miio_yeelink/fan.py", line 26, in async_setup_entry
await async_setup_platform(hass, config, async_add_entities)
File "/config/custom_components/miio_yeelink/fan.py", line 56, in async_setup_platform
entity = MiotFanEntity(config)
File "/config/custom_components/miio_yeelink/__init__.py", line 997, in __init__
self._device = MiotDevice(self.mapping, host, token)
File "/usr/local/lib/python3.8/site-packages/miio/miot_device.py", line 48, in __init__
super().__init__(ip, token, start_id, debug, lazy_discover, timeout)
File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 151, in __init__
self._protocol = MiIOProtocol(
File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 43, in __init__
self.token = bytes.fromhex(token)
ValueError: non-hexadecimal number found in fromhex() arg at position 3

_Originally posted by @oscarliuyc in https://github.com/al-one/hass-miio-yeelink/issues/18#issuecomment-857409228_

**Comment by al-one** [comment]
你的HA版本是多少？

**Comment by oscarliuyc** [comment]
> 
> 
> 你的HA版本是多少？

Home Assistant 2021.6.3
情况是，插件可以自动识别型号，可以显示风扇和灯的状态，可是不能控制。手动加入型号的话，插件不能显示任何Device 和Entities.

之前插件是正常运作的。我尝试从新安装旧插件版本，可是找不到Miio-yeelink 输入资料（IP, Token, Model, Mode) 的画面。

麻烦你。不好意思。

**Comment by al-one** [comment]
请更新到最新版本再试。

**Comment by oscarliuyc** [comment]
> 
> 
> 请更新本插件到最新版本再试。

It works.  Thank a million.

搞定了。万分感谢！
