### ISSUE TITLE
yeelink.bhf_light.v5无法开启“排气”、“暖风”以及“吹风”模式，提示NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by zhtengw** [al-one/hass-miio-yeelink#2]
```
2021-01-05 09:05:03 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140177991987648] name 'self' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/lib/python3.8/site-packages/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/lib/python3.8/site-packages/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/etc/homeassistant/custom_components/miio_yeelink/__init__.py", line 593, in async_turn_on
    spd = self.speed_to_gears(speed or SPEED_HIGH) if hasSpeed else 0
  File "/etc/homeassistant/custom_components/miio_yeelink/__init__.py", line 630, in speed_to_gears
    spd = 2 if self._mode == 'warmwind' else 3
NameError: name 'self' is not defined
```

目前将__init__.py line 630改成`spd = 2`暂时用着

**Comment by al-one** [comment]
[v0.1.4](https://github.com/al-one/hass-miio-yeelink/releases/tag/v0.1.4) 已修复
