### ISSUE TITLE
yeelink.light.fancl1 connection failed after recent upgrade

### ISSUE THREAD

**Issue by oscarliuyc** [al-one/hass-miio-yeelink#28]
Hi, after the recent upgrade of this integration, both my yeelink.light.fancl1 could no longer work.  Appreciate it if you could help look into it:

```
Logger: homeassistant.components.fan
Source: custom_components/miio_yeelink/__init__.py:222
Integration: Fan (documentation, issues)
First occurred: 10:23:23 AM (1 occurrences)
Last logged: 10:23:23 AM

Error while setting up miio_yeelink platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/miio_yeelink/fan.py", line 27, in async_setup_entry
    await async_setup_platform(hass, config, async_add_entities)
  File "/config/custom_components/miio_yeelink/fan.py", line 66, in async_setup_platform
    entity = MiotFanEntity(config)
  File "/config/custom_components/miio_yeelink/__init__.py", line 1079, in __init__
    self._device = MiotDevice(ip=host, token=token)
  File "/config/custom_components/miio_yeelink/__init__.py", line 222, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/miio/miot_device.py", line 50, in __init__
    raise DeviceException(
miio.exceptions.DeviceException: Neither the class nor the parameter defines the mapping

```
```

Logger: homeassistant.components.light
Source: custom_components/miio_yeelink/__init__.py:222
Integration: Light (documentation, issues)
First occurred: 10:23:22 AM (1 occurrences)
Last logged: 10:23:22 AM

Error while setting up miio_yeelink platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/miio_yeelink/light.py", line 49, in async_setup_entry
    await async_setup_platform(hass, config, async_add_entities)
  File "/config/custom_components/miio_yeelink/light.py", line 59, in async_setup_platform
    entity = MiotLightEntity(config)
  File "/config/custom_components/miio_yeelink/__init__.py", line 962, in __init__
    self._device = MiotDevice(ip=host, token=token, mapping=self.mapping)
  File "/config/custom_components/miio_yeelink/__init__.py", line 222, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/miio/miot_device.py", line 50, in __init__
    raise DeviceException(
miio.exceptions.DeviceException: Neither the class nor the parameter defines the mapping

```

**Comment by al-one** [comment]
What is your HA version ?

**Comment by oscarliuyc** [comment]
Home Assistant 2021.9.7
