### ISSUE TITLE
yeelink.bhf_light.v5 initial error with v0.1.4

### ISSUE THREAD

**Issue by zhtengw** [al-one/hass-miio-yeelink#3]
The HA log shows:
`
Logger: homeassistant.components.fan
Source: custom_components/miio_yeelink/fan.py:51
Integration: 风扇 (documentation, issues)
First occurred: 上午9:52:32 (2 occurrences)
Last logged: 上午10:05:53
Error while setting up miio_yeelink platform for fan

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/etc/homeassistant/custom_components/miio_yeelink/fan.py", line 26, in async_setup_entry
    await async_setup_platform(hass, config, async_add_entities)
  File "/etc/homeassistant/custom_components/miio_yeelink/fan.py", line 51, in async_setup_platform
    entity = BathHeaterEntityV5(cfg, m, prt)
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given
`

**Comment by al-one** [comment]
fixed in [v0.1.5](https://github.com/al-one/hass-miio-yeelink/releases/latest)
