### ISSUE TITLE
yeelink.light.fancl2 vs v0.1.9 - doesn't work

### ISSUE THREAD

**Issue by GregoryZet** [al-one/hass-miio-yeelink#32]
After upgrade Xiaomi Miio For Yeelink to version 0.1.9  the yeelink.light.fancl2 stops working:
LIGHT ERROR:
"
Logger: homeassistant.components.light
Source: custom_components/miio_yeelink/__init__.py:222
Integration: Światło (documentation, issues)
First occurred: 18:31:34 (1 occurrences)
Last logged: 18:31:34
Error while setting up miio_yeelink platform for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/miio_yeelink/light.py", line 49, in async_setup_entry
    await async_setup_platform(hass, config, async_add_entities)
  File "/config/custom_components/miio_yeelink/light.py", line 59, in async_setup_platform
    entity = MiotLightEntity(config)
  File "/config/custom_components/miio_yeelink/__init__.py", line 962, in __init__
    self._device = MiotDevice(ip=host, token=token, mapping=self.mapping)
  File "/config/custom_components/miio_yeelink/__init__.py", line 222, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/miio/miot_device.py", line 50, in __init__
    raise DeviceException(
miio.exceptions.DeviceException: Neither the class nor the parameter defines the mapping

"

FAN ERROR:
"
Logger: homeassistant.components.fan
Source: custom_components/miio_yeelink/__init__.py:222
Integration: Wentylator (documentation, issues)
First occurred: 18:31:33 (1 occurrences)
Last logged: 18:31:33
Error while setting up miio_yeelink platform for fan

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/miio_yeelink/fan.py", line 27, in async_setup_entry
    await async_setup_platform(hass, config, async_add_entities)
  File "/config/custom_components/miio_yeelink/fan.py", line 66, in async_setup_platform
    entity = MiotFanEntity(config)
  File "/config/custom_components/miio_yeelink/__init__.py", line 1079, in __init__
    self._device = MiotDevice(ip=host, token=token)
  File "/config/custom_components/miio_yeelink/__init__.py", line 222, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/miio/miot_device.py", line 50, in __init__
    raise DeviceException(
miio.exceptions.DeviceException: Neither the class nor the parameter defines the mapping
"
Under version 0.1.8 everything is OK.

Home Assistant version: 2021.1.6

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-miio-yeelink/commit/e02a3daaec0c55309e68cbb05d44508f7e873dc1

**Comment by GregoryZet** [comment]
I confirm that this fix (e02a3da) resolve problem. Yeelink.light.fancl2 starts working correct under v.0.1.9.

Thanks for help.
