### ISSUE TITLE
error changing brightness level 

### ISSUE THREAD

**Issue by FlashingGremlin** [al-one/hass-miio-yeelink#34]
Hi, Can you help please?
Every time I try to change the brightness level this error appears:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/yeelight/light.py:271
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:38:46 PM (2 occurrences)
Last logged: 6:38:48 PM

[2822626008] Error when calling async_set_default for bulb Yeelight Ceilb 0x1790c239 at 192.168.1.121: {'code': -5006, 'message': 'illegal request'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 250, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 700, in async_set_default
    await self._bulb.async_set_default()
  File "/usr/local/lib/python3.9/site-packages/yeelight/aio.py", line 36, in wrapper
    cmd = await self.async_send_command(
  File "/usr/local/lib/python3.9/site-packages/yeelight/aio.py", line 75, in async_send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: {'code': -5006, 'message': 'illegal request'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 496, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 798, in async_turn_on
    await self.async_set_default()
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 271, in _async_wrap
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error when calling async_set_default for bulb Yeelight Ceilb 0x1790c239 at 192.168.1.121: {'code': -5006, 'message': 'illegal request'}

**Comment by FlashingGremlin** [comment]
Hello, the cause of the error, is the "Save Status on Change" option in the configuration of the integration.
Can someone figure out why?
Thx!

**Comment by al-one** [comment]
- https://www.home-assistant.io/integrations/yeelight
- https://github.com/home-assistant/core/issues?q=is%3Aissue+label%3A%22integration%3A+yeelight%22
