### ISSUE TITLE
yeelink.light.ceiling5 not working with latest update of HA

### ISSUE THREAD

**Issue by rotrials** [al-one/hass-miio-yeelink#51]
Hello,

With the latest update of the HA my yeelight ceiling is not working anymore, I got the following error:

`Logger: homeassistant.config_entries
Source: components/xiaomi_miio/__init__.py:470
First occurred: 9:59:58 PM (3 occurrences)
Last logged: 10:10:46 PM

Error unloading entry Front door light for xiaomi_miio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 470, in async_unload_entry
    hass.data[DOMAIN].pop(config_entry.entry_id)
KeyError: 'e8a810337c8cfdd32cec79b3d45dae41'`

`Logger: homeassistant.components.light
Source: components/xiaomi_miio/light.py:566
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 9:58:08 PM (2 occurrences)
Last logged: 10:10:39 PM

xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 735, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 566, in async_update
    self._brightness = ceil((255 / 100.0) * state.brightness)
TypeError: can't multiply sequence by non-int of type 'float'`

Let me know in case you further details.

Thank you.

**Comment by rotrials** [comment]
Fot the other users, it was fixed with [https://github.com/al-one/hass-miio-yeelink/commit/7bef5630cccc77210c611ddb44420d632371decc](url)
