### ISSUE TITLE
yeelink.light.fancl2调用miio_yeelink.send_command服务时提示‘str' object has no attribute 'get’

### ISSUE THREAD

**Issue by zhtengw** [al-one/hass-miio-yeelink#7]
逸扬风扇灯调用miio_yeelink.send_command服务时，会有错误提示：
```
2021-01-14 00:44:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139623714830752] 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/lib/python3.8/site-packages/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/lib/python3.8/site-packages/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/etc/homeassistant/custom_components/miio_yeelink/__init__.py", line 179, in async_service_handler
    await getattr(dvc, fun)(**params)
  File "/etc/homeassistant/custom_components/miio_yeelink/__init__.py", line 318, in async_command
    result = await self._try_command(mask_error, self._device.send, method, params)
  File "/etc/homeassistant/custom_components/miio_yeelink/__init__.py", line 307, in _try_command
    return result.get('code', 1) == self._success_result
AttributeError: 'str' object has no attribute 'get'
```
但实际上服务是调用成功了的，比如在关灯情况下用以下参数调用miio_yeelink.send_command，灯会打开
```
entity_id: light.can_ting_deng
method: set_power
params:
  - 'on'
```

**Comment by al-one** [comment]
`yeelink.light.fancl2`使用的是miot协议，应该使用`miio_yeelink.set_property`服务：
```yaml
service: miio_yeelink.set_property
data:
  entity_id: light.yeelight_entity_id
  field: power
  value: true
```
send_command能执行成功是因为该设备同样支持旧版miio协议

**Comment by zhtengw** [comment]
> 
> 
> `yeelink.light.fancl2`使用的是miot协议，应该使用`miio_yeelink.set_property`服务：
> 
> ```yaml
> service: miio_yeelink.set_property
> data:
>   entity_id: light.yeelight_entity_id
>   field: power
>   value: true
> ```
> 
> send_command能执行成功是因为该设备同样支持旧版miio协议

用set_property 服务可以控制power开关，也没有错误提示了，但控制夜灯模式好像不生效，用`set_command`服务可以通过`set_ps nightlight on`来打开夜灯模式，但状态属性里的nighttime值没有变化。
