### ISSUE TITLE
homeassistant log

### ISSUE THREAD

**Issue by bossben8** [al-one/hass-miio-yeelink#77]
ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1716058984] BathHeaterEntityV5.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 334, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BathHeaterEntityV5.async_turn_on() takes from 1 to 2 positional arguments but 3 were given

**Comment by stone5202** [comment]
I've got the same question

**Comment by walking-octopus** [comment]
Can reproduce.

**Comment by AlexAl77** [comment]
Dear author, please release a bug update.

**Comment by walking-octopus** [comment]
Update: The issue resolved on its own.

However, after reading the log provided, I see no mention of `miio-yeelink` integration. It just talks about some boiler or something...

Can anyone still experiencing the issue post actually relevant logs?

**Comment by AlexAl77** [comment]
Failed to call fan/turn_on service. BathHeaterEntity.async_turn_on() takes from 1 to 2 positional arguments but 3 were given

Tell me how to send me the logs, where are they located? After the update, the bathroom dryer stopped responding, you can only control the light

**Comment by stone5202** [comment]
I have solved this problem probably
u need to change the code in the file => /homeassistant/custom_components/miio_yeelink/__init__.py
first, find the version of your device
and find async_turn_on
change the code to
    async def async_turn_on(self, speed=None, preset_mode=None) -> None:
        _LOGGER.debug('Turning on for %s. speed: %s, preset_mode: %s', self._name, speed, preset_mode)
final, reboot your home assistant
I'm just an amateur, but making these adjustments indeed temporarily resolved the issue I encountered

**Comment by AlexAl77** [comment]
#    async def async_turn_on(self, speed: str = None, **kwargs) -> None:
#    Fix for HA 2023.12.2 where turn_on would not work anymore.
    async def async_turn_on(self, speed: str = None, mode: str = None, **kwargs) -> None:
