### ISSUE TITLE
Error in HA 2024.11.0

### ISSUE THREAD

**Issue by Estirao** [al-one/hass-miio-yeelink#94]
The integration does not load and gives the following error:

Registrador: homeassistant.setup
Fuente: setup.py:334
Ocurrió por primera vez: 21:34:36 (1 ocurrencias)
Última vez registrado: 21:34:36

Setup failed for custom integration 'miio_yeelink': Unable to import component: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/miio_yeelink/__init__.py", line 11, in <module>
    from homeassistant.config import DATA_CUSTOMIZE
ImportError: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/miio_yeelink/__init__.py", line 11, in <module>
    from homeassistant.config import DATA_CUSTOMIZE
ImportError: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)

**Comment by arierom70** [comment]
Same problem.

**Comment by Estirao** [comment]
It works! If we replace the line ‘from homeassistant.config import DATA_CUSTOMIZE’ with ‘from homeassistant.core_config import DATA_CUSTOMIZE’ in the file ‘custom_components/miio_yeelink/_init.py’, everything returns to normal.

**Comment by 17josue17** [comment]
> It works! If we replace the line ‘from homeassistant.config import DATA_CUSTOMIZE’ with ‘from homeassistant.core_config import DATA_CUSTOMIZE’ in the file ‘custom_components/miio_yeelink/_init.py’, everything returns to normal.

Lot of thanks¡¡¡¡¡

**Comment by arierom70** [comment]
Works perfectly . Thanks

**Comment by HaruIjima-kun** [comment]
> It works! If we replace the line ‘from homeassistant.config import DATA_CUSTOMIZE’ with ‘from homeassistant.core_config import DATA_CUSTOMIZE’ in the file ‘custom_components/miio_yeelink/_init.py’, everything returns to normal.

Same problem, your solution works perfectly! Thanks!

**Comment by romanr** [comment]
uh oh.. I was sitting now under lamp that could not be turned off.  
same "cannot import name 'DATA_CUSTOMIZE'"

To make clear @Estirao advice,
Edit the file and change like this, change `.config` to `.core_config`:

![Home Assistant-Home Assistant-1108 0735@2x](https://github.com/user-attachments/assets/0e85de40-5fbd-4f4c-95ae-6554e23ea2b0)

Reload configuration didn't help for me, only "Restart Home Assistant".
![Home Assistant-Home Assistant-1108 0733@2x](https://github.com/user-attachments/assets/f9a801c7-cb05-436e-a076-16d043b12521)

**Comment by CuccioloDiInformatico** [comment]
Same issue
